config/routes.rb
Railsblog::Application.routes.draw do
  
  resources :posts do
    resources :comments
  end

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  # Posts have comments, and tell Rails to automagically delete all comments for a post when it is deleted
  has_many :comments, dependent: :destroy

  # Only let Posts be created that a) have a title, and b) the title has to have at least 5 characters
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # See posts controller. This time, we only force the name/password when they try to delete a comment.
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    # A Comment belongs to only one Post, so find the Post this Comment will be attached to
    @post = Post.find(params[:post_id])
    # Create a Comment that's linked to the Post and fill it with the commenter's name and his/her comment
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    # A Comment belongs to only one Post, so find the Post this Comment will be attached to
    @post = Post.find(params[:post_id])
    # Grab the comment we're trying to delete
    @comment = @post.comments.find(params[:id])
    # Delete the comment
    @comment.destroy
    # Send the user back to the Post you deleted the Comment from.
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # Force the user to type the correct username and password to do anything in the Posts controller except for viewing the index or a single post. Feel free to change the name/password to something else.
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  before_action :get_blog_post, except: [:new, :create, :index]

  def index
    # Create a @posts instance variable and fill it with all the posts in the database
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    # The before_action found the post & assigned it to @post
  end

  def edit
    # The before_action found the post & assigned it to @post
  end

  def update
    # The before_action found the post & assigned it to @post

    if @post.update(post_params)
      # Add a message in the Rails flash hash
      flash[:notice] = 'Awesomesauce! That post looks much better.'
      # If @post updated correctly, redirect the user to it
      redirect_to @post
    else
      # Send the user back to the form to try again
      render 'edit'
    end
  end

  def create
    # Create a new instance of the Post model with the params (title & body) that came from the form
    @post = Post.new(post_params)

    # Try to actually save the post to the database instead of just holding it in memory
    if @post.save
      # Add a message in the Rails flash hash
      flash[:notice] = "Success! That's one fine-looking post."
      # If @post saved correctly, redirect the user to it
      redirect_to @post
    else
      # Otherwise, send the user back to the form to try again
      render 'new'
    end
  end

  def destroy
    # The before_action found the post & assigned it to @post, so nuke it!
    @post.destroy
    # Add a message in the Rails flash hash
    flash[:notice] = 'Success! That post is history.'
    # Go back to the listing of all the posts
    redirect_to posts_path
  end


  # Methods below 'private' can only be acessed by methods inside this controller. There's no way to visit the route /posts/post_params. 
  private

    def get_blog_post
      @post = Post.find(params[:id])
    end

    # Good ol' Rails 4 Strong Parameters...
    # http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters
    def post_params
      # Remember how we created a new Post from the params? This line tells Rails to only allow the title and body to be set from the params. It's a major security improvement, but it seems wonky at first.
      params.require(:post).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Shamelessly ripped from Michael Hartl's Rails tutorial:
  # http://ruby.railstutorial.org/chapters/rails-flavored-ruby#sec-back_to_the_title_helper
  def full_title(page_title)
    base_title = "Rails Blog"

    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  # Returns the meta description on a per-page basis.
  def meta_description(page_descripton)
    if page_descripton.empty?
      "A sweet blogging application inspired by the official Ruby on Rails tutorial."
    else
      "#{page_descripton}"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %>:</strong>
  <%= comment.body %>
  <%= link_to '(x)', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= render 'shared/form_errors' %>

  <div class="form-inputs">
    <%= f.input :commenter, autofocus: true %>
    <%= f.input :body, as: :text, input_html: { cols: 100, rows: 5 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="messages text-center alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="<%= meta_description(yield(:description)) %>">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="body-container" class='container-narrow shadow rounded'>

    <%= render 'layouts/messages' %>

    <%= yield %>
  
  </div> 

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= render 'shared/form_errors' %>

  <div class="form-inputs">
    <%= f.input :title, autofocus: true %>
    <%= f.input :text, as: :text, input_html: { cols: 100, rows: 5 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class='text-center'>Editing: <%= @post.title %></h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% provide(:title, "All Posts") %>

<h1 class='text-center'>All Yo' Posts</h1>

<p class='text-center'>
  <%= link_to 'New post', new_post_path, class: 'btn btn-primary btn-large' %>
</p>

<% if @posts.any? %>
  <%= pluralize(@posts.count, 'post') %>

  <table class="table table-striped table-bordered table-hover">
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Text</th>
      <th></th>
      <th></th>
    </tr>

    <% @posts.each do |post| %>
      <tr>
        <th><%= post.id %></th>
        <td><%= link_to post.title, post %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to '(x)', post_path(post),
                  method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h3 class="alert alert-success text-center">Come on now, let's get blogging!</h3>
<% end %>

app/views/posts/new.html.erb
<h1>Write Something!</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

<!-- Generate copyright-free dummy text for testing: http://www.lipsum.com -->

app/views/posts/show.html.erb
<!-- SEO, baby! Check application_helper.rb & application.html.erb for more info -->
<% provide(:title, @post.title) %>
<!-- http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-truncate -->
<% provide(:description, truncate(@post.text, length: 140)) %> 

<h2 class="text-center"><%= @post.title %></h2>
 
<p>
  <%= @post.text %>
</p>

<hr>

<% if @post.comments.any? %>
  <!-- http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-pluralize -->
  <h4>
    <%= pluralize(@post.comments.count, 'Comment') %>
  </h4>
  <%= render @post.comments %>
<% else %>
  <h4>No comments...</h4>
<% end %>
 
<hr>

<h4>Got something to say?</h4>
<%= render "comments/form" %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/shared/_form_errors.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation", class="alert alert-error">
    <a class="close" data-dismiss="alert">&#215;</a>
    <h4>Houston, we have a problem...</h4>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<!-- I don't like putting 'controller:' in my views unless I have to, but it works. -->
<%#= link_to "My Blog", controller: "posts" %>

<!-- This is how Rails prefers it: use the link helpers: -->
<%= link_to "My Blog", posts_path %>